#!/usr/bin/env bash

#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# get location of the script
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# version will be overwritten my Maven-Antrun-Plugin
INFERENCE_LIB_JAR=VERSION_TMP

# the path to the Inference distribution Jar file relative to the current
INFERENCE_LIB=$DIR/../lib/$INFERENCE_LIB_JAR

# check whether environment variable SPARK_HOME was set
if [ -z "${SPARK_HOME}" ]; then
    echo "You have to set the environment variable SPARK_HOME, which maps to the home directory of the Spark distribution."
    exit 1
fi 

# submit the Spark job
exec "${SPARK_HOME}"/bin/spark-submit "$INFERENCE_LIB" "$@"
