PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX foaf: <http://xmlns.com/foaf/spec/>
PREFIX schema: <http://schema.org/>
PREFIX rev: <http://purl.org/stuff/rev#>
PREFIX edm: <http://www.europeana.eu/schemas/edm/>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX gr: <http://purl.org/goodrelations/v1#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX bsbm: <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/>

SELECT DISTINCT ?label ?value
WHERE {
    ?product rdfs:label ?label .
    ?product bsbm:productPropertyNumeric1 ?value .
    ?product rdf:type bsbm:Product .
    ?product bsbm:producer ?producer .
    ?producer rdf:type bsbm:Producer .
    ?producer foaf:homepage ?hp .
    ?review bsbm:reviewFor ?product .
    ?review rdf:type schema:Review .
    ?review rev:reviewer ?pers .
    ?pers foaf:name ?fn .
    ?pers edm:country ?cn .
    ?offer bsbm:product ?product .
    ?offer rdf:type schema:Offer .
    FILTER (?value > 102)
}
ORDER BY ?label
LIMIT 10