PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX foaf: <http://xmlns.com/foaf/spec/>
PREFIX schema: <http://schema.org/>
PREFIX rev: <http://purl.org/stuff/rev#>
PREFIX edm: <http://www.europeana.eu/schemas/edm/>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX gr: <http://purl.org/goodrelations/v1#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX bsbm: <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/>

SELECT DISTINCT ?productLabel ?simProperty1 ?simProperty2
WHERE {
    ?product rdfs:label ?productLabel .
    ?product bsbm:productPropertyNumeric1 ?simProperty1 .
    ?product bsbm:productPropertyNumeric2 ?simProperty2 .
    ?product bsbm:producer ?producer .
    ?review bsbm:reviewFor ?product .
    ?review rdf:type schema:Review .
    ?offer bsbm:product ?product .
    ?offer rdf:type schema:Offer .
    FILTER (?simProperty1 < 120)
    FILTER (?productLabel != "wineskins banded crc")
    FILTER (?simProperty2 < 170)
}
ORDER BY ?productLabel
LIMIT 5
