PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX foaf: <http://xmlns.com/foaf/spec/>
PREFIX schema: <http://schema.org/>
PREFIX rev: <http://purl.org/stuff/rev#>
PREFIX edm: <http://www.europeana.eu/schemas/edm/>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX gr: <http://purl.org/goodrelations/v1#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX bsbm: <http://www4.wiwiss.fu-berlin.de/bizer/bsbm/v01/vocabulary/>

SELECT ?productLabel ?price ?vendor ?revTitle
?reviewer ?rating1 ?rating2 ?product ?revName
WHERE {
    ?product rdfs:label ?productLabel .
    ?product rdf:type bsbm:Product .
    ?offer bsbm:product ?product .
    ?offer bsbm:price ?price .
    ?offer bsbm:vendor ?vendor .
    ?offer bsbm:validTo ?date .
    ?review bsbm:reviewFor ?product .
    ?review rev:reviewer ?reviewer .
    ?review dc:title ?revTitle .
    ?review bsbm:rating1 ?rating1 .
    ?review bsbm:rating2 ?rating2 .
    ?reviewer foaf:name ?revName .
    ?reviewer a foaf:Person .
    FILTER (?price > 5000)
    FILTER (?product = 9)
}
