title: "SANSA Stack"
#remote_theme: pmarsceill/just-the-docs
search_enabled: true
logo: "assets/images/sansa-logo-blue.png"
markdown: kramdown
kramdown:
  parse_block_html: true


exclude:
  - sansa*
  - javadoc
  - scaladocs

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/SANSA-Stack/SANSA-Stack" # the github URL for your repo
gh_edit_branch: "develop" # the branch that your docs is served from
gh_edit_source: "docs" # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately


remote_theme: carlosperate/jekyll-theme-rtd
repo_url: 'https://github.com/SANSA-Stack/SANSA-Stack'

edit_on_github: true
github_docs_folder: false
sticky_navigation: true
prev_next_buttons_location: both
search_enabled: true
hljs_style: github
