FROM bde2020/spark-java-template:1.6.2-hadoop2.6

MAINTAINER Gezim Sejdiu <g.sejdiu@gmail.com>

ENV SPARK_APPLICATION_JAR_NAME sansa-examples-spark-1.1-with-dependencies

ENV HDFS_URL=hdfs://hdfs:9000
