FROM bde2020/spark-java-template:1.5.1-hadoop2.6

MAINTAINER Gezim Sejdiu <g.sejdiu@gmail.com>

ENV SPARK_APPLICATION_MAIN_CLASS net.sansa_stack.examples.spark.rdf.TripleReader
ENV SPARK_APPLICATION_JAR_NAME sansa-examples-spark-1.1-with-dependencies

ENV HDFS_URL=hdfs://hdfs:9000
